ticker:
  input:
    dir: /home/cgms/inputData
    charset: euc-kr
  output:
    dir: /home/cgms/outputData
  broadcast:
    date:
      format: yyyyMMddHHmmss
log:
  config:
    path: /home/cgms/logs
    filename:
      standard: catalina.log
      error: error.log
    maxHistory: 7
    totalSizeCap: 10MB
api:
  baseUrl: http://10.13.14.1:5005
  pushUrl: /pcms/push
  pollingUrl: /pcms/status/
  pollingRetryUrl: /pcms/statusretry/
  retry:
    delayTime: 3000