ticker:
  input:
    dir: /home/cgms/inputData
    charset: euc-kr
  output:
    dir: /home/cgms/outputData
  broadcast:
    date:
      format: yyyyMMddHHmmss
log:
  config:
    path: /home/cgms/logs
    filename:
      info: log
      error: err
    maxHistory: 7
    totalSizeCap: 10MB