ticker:
  input:
    dir: C:\home\cgms\inputData
    charset: euc-kr
  output:
    dir: C:\home\cgms\outputData
  broadcast:
    date:
      format: yyyyMMddHHmmss
log:
  config:
    path: /home/cgms/logs
    filename:
      info: log
      error: err
    maxHistory: 7
    totalSizeCap: 10MB
api:
  baseUrl: http://localhost:8080
  pushUrl: /pcms/push
  pollingUrl: /pcms/status/
  pollingRetryUrl: /pcms/statusretry/