ticker:
  input:
    dir: C:\home\cgms\inputData
    charset: euc-kr
  output:
    dir: C:\home\cgms\outputData
  broadcast:
    date:
      format: yyyyMMddHHmmss
log:
  config:
    path: C:\home\cgms\logs
    filename:
      standard: catalina.log
      error: error.log
    maxHistory: 30
    totalSizeCap: 10MB
api:
#  baseUrl: http://localhost:8080
  baseUrl: http://10.13.14.1:5005
  pushUrl: /pcms/push
  pollingUrl: /pcms/status/
  pollingRetryUrl: /pcms/statusretry/
  retry:
    delayTime: 3000