ticker:
  input:
    dir: C:\home\cgms\inputData
    charset: euc-kr
  output:
    dir: C:\home\cgms\outputData
  broadcast:
    date:
      format: yyyyMMddHHmmss
log:
  config:
    path: C:\home\cgms\logs
    filename:
      info: log
      error: err
    maxHistory: 30
    totalSizeCap: 10MB